<?php
/*
 * tab.phtml
 * 
 * Copyright (c) 2012 Aftab Naveed <aftabnaveed@gmail.com>. 
 * 
 * This file is part of Displaze Web Services Inc..
 * 
 * Displaze Web Services Inc. is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Displaze Web Services Inc. is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Displaze Web Services Inc..  If not, see <http ://www.gnu.org/licenses/>.
 */
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Manufacturer'); ?></h4>
    </div>
    <div id="group_fields4" class="fieldset fieldset-wide">
        <div class="hor-scroll">
            <table cellspacing="0" class="form-list">
                <tbody>
                    <tr>
                        <td>
                            <table cellspacing="0" class="form-list">
                                <tbody>
                                    <tr>
                                        <td class="label">
                                            <label for="enablenew">
                                               <?php echo $this->__('Select Manufacturer'); ?>
                                            </label>
                                        </td>
                                        <td class="value">


                                            <select class=" select" name="manufacturers_id" id="manufacturer_id">
                                                <option value="0"><?php echo $this->__('No Manufacturer'); ?></option>
                                                <?php foreach ($this->getManufacturerCollection() as $_manufacturer) : ?>
                                                    <?php if ($this->getProduct()->getManufacturerId() == $_manufacturer->getId()): ?>
                                                        <option selected="selected" value="<?php echo $_manufacturer->getId(); ?>">
                                                            <?php echo $_manufacturer->getTitle(); ?>
                                                        </option>
                                                    <?php else: ?>
                                                        <option value="<?php echo $_manufacturer->getId(); ?>">
                                                            <?php echo $_manufacturer->getTitle(); ?>
                                                        </option>
                                                    <?php endif; ?>     

                                                <?php endforeach; ?> 
                                            </select>
                                        </td>
                                        <td class="scope-label"><span class="nobr"></span></td>
                                        <td><small>&nbsp;</small></td>
                                    </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>