<?php
/*
 * link.phtml
 * 
 * Copyright (c) 2012 Aftab Naveed <aftabnaveed@gmail.com>. 
 * 
 * This file is part of Displaze Web Services Inc..
 * 
 * Displaze Web Services Inc. is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Displaze Web Services Inc. is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Displaze Web Services Inc..  If not, see <http ://www.gnu.org/licenses/>.
 */
?>

<!--Code to include shopby brand menu -->
<?php $manufacturerCollection = $this->getManufacturerCollection(); ?>
<?php if (count($manufacturerCollection) != 0) : ?>
    <li class="current shop-by-brand">
        <a href="#"><?php echo $this->__('Shop By Brand') ?></a>
        <ul>
            <?php foreach ($manufacturerCollection as $_manufacturer) : ?>
                <li>
                    <a href="<?php echo Mage::helper('mybrand/manufacturer')->getUrl($_manufacturer->getIdentifier()); ?>" class="">
                        <span><?php echo $this->htmlEscape($_manufacturer->getTitle()) ?></span>
                    </a>
                </li>
            <?php endforeach ?>
        </ul>
    </li>
<?php endif; ?>